let numbers = [10, 20, 30, 10, 40, 20, 50, 60, 60];
let unique = [...new Set(numbers)];
console.log(unique);
let secondLargest = [...new Set(numbers)].sort((a, b) => b - a)[1];
console.log(secondLargest);
let frequency = numbers.reduce((f, n) => {
  f[n] = (f[n] || 0) + 1;
  return f;
}, {});
console.log(frequency);
let firstNonRepeat = numbers.find(n => frequency[n] === 1);
console.log(firstNonRepeat);
let rotated = [...numbers.slice(2), ...numbers.slice(0, 2)];
console.log(rotated);
let nested = [1,2,[3,4,[5]]];
let flat = nested.flat(Infinity);
console.log(flat);
let arr = [1,2,3,5,6];
let missing = ((arr.length + 1) * (arr.length + 2)) / 2 - arr.reduce((a,b)=>a+b,0);
console.log(missing);